apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1 # Forcefully a single replica
  template:
    spec:
      containers:
        - name: registry
          env:
            - { name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY, value: '/var/lib/registry' }
          volumeMounts:
            - { name: storage, mountPath: '/var/lib/registry' }
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: registry
