apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  template:
    spec:
      enableServiceLinks: false
      containers:
        - name: registry
          image: registry:latest
          ports:
            - { containerPort: 5000, name: http }
            - { containerPort: 5001, name: metrics }
          volumeMounts:
            - { name: config, mountPath: '/etc/docker/registry' }
          livenessProbe:
            httpGet:
              port: metrics
              path: /debug/health
          readinessProbe:
            httpGet:
              port: metrics
              path: /debug/health
      volumes:
        - name: config
          configMap:
            name: registry-config
