apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-instance
  labels:
    g4b1bb097.dev/prometheus: 'true'
spec:
  selector:
    matchLabels:
      operated-prometheus: 'true'
  endpoints:
    - port: web
