commonLabels:
  app.kubernetes.io/name: grafana
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: grafana
    newTag: 7.1.0
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: grafana-config
    files:
      - grafana.ini
  - name: grafana-dashboards
  - name: grafana-datasources