---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.16.0
  values:
    installCRDs: true
    extraArgs:
      - --enable-certificate-owner-ref=true
