---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.11.1
  values:
    controller:
      config:
        server-tokens: 'false'
        enable-brotli: 'true'
        proxy-next-upstream: 'error timeout invalid_header http_500 http_502 http_503 http_504'
      kind: Deployment
      service:
        type: LoadBalancer
      metrics:
        enabled: true
      defaultBackend:
        enabled: true
